name: Chocolatey Community Validation Builds

on:
  # Trigger on pushes and pull requests
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build on Windows
  windows-build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache Tools
        uses: actions/cache@v3.0.11
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
      - name: Build with .NET Framework
        run: ./build.ps1 --verbosity=diagnostic --target=CI --testExecutionType=unit --shouldRunOpenCover=false
      - name: Upload Windows build results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: windows-build-results
          path: |
            code_drop\TestResults\issues-report.html
            code_drop\TestResults\NUnit\TestResult.xml
            code_drop\TestCoverage\lcov.info
            code_drop\TestCoverage\OpenCover.xml
            code_drop\MsBuild.log
# TODO: Add step to upload codecov results?